[package]
name = "visualization_tool"
version = "0.1.0"
authors = ["Your Name <your.email@example.com>"]
description = "A visualization tool for Solana CPI"
license = "MIT"

[dependencies]
anchor-lang = "0.23.0"  # Match this to the version you've installed

[profile.dev]
opt-level = 2

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
visualization_tool = "2qHoXFewzDWEps3dHZmd7XrUB8VwL5KBjB2rHwrzxQLj"  # Replace with your localnet program ID

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"  # Change to "Devnet", "Testnet", or "Mainnet Beta" as needed
wallet = '~\.config/solana/id.json'  # Path to your Solana wallet

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
